### ISSUE TITLE
Error in result_fetch(res@ptr, n) : Error fetching buffer: (but not in RMySQL)

### ISSUE THREAD

**Issue by zhilizheng** [r-dbi/RMariaDB#90] opened 2018-03-09 04:16 UTC
I tried to connect my database by RMariaDB:

library(DBI)
con <- dbConnect(RMariaDB::MariaDB(),group="test")
dbListTables(con)

Prompts:
Error in result_fetch(res@ptr, n) : Error fetching buffer:

However, when I try in RMySQL:
con <- dbConnect(RMySQL::MySQL(),group="test")
dbListTables(con)
It returns the tables correctly. 

It seems there are some problems in RMariaDB package. 

All packages were installed freshly, so it the latest version in R repos.

**Comment by jtelleriar** [comment] 2018-03-09 07:45
Try changing the MariaDB C# Connector to the MySQL one :)

It might work.

**Comment by zhilizheng** [comment] 2018-03-15 00:35
library(DBI)
con <- dbConnect(RMariaDB::MariaDB(),group="test")
# empty, won't has the problem
dbListTables(con)
# write a data
test=data.frame(x=c(1,2,3), y=c("1", "c2", "c3"))
dbWriteTable(con, "test", test)
# Error in result_fetch(res@ptr, n) : Error fetching buffer:
dbListTables(con)

I think this is the problem of RMariaDB.   I use MariaDB, the connector is from MariaDB.  However,  I can get RMySQL work well compiled with MariaDB, but can not get RMariaDB work compile with MariaDB.

**Comment by krlmlr** [comment] 2018-05-01 00:12
Thanks. This looks like a duplicate of #69, which is resolved by updating Connector/C to a *very* recent version. *RMySQL* used other means to communicate query parameters to the database server and was not affected by these (presumed) problems in Connector/C.

**Closed** 2018-10-02 20:53 UTC
