### ISSUE TITLE
Issues with Date format if earlier than 1970-01-01 

### ISSUE THREAD

**Issue by PaolaCognigni** [r-dbi/RMariaDB#114] opened 2018-11-06 09:35 UTC
Hi there,
R's been crashing when I try to dbWriteTable a data frame that contains Date fields with negative (pre-1970) values:

```
library(DBI)
conSQL <- dbConnect(RMariaDB::MariaDB(), etc etc)
datetest<-data.frame("today"=Sys.Date(),"yesterday"=Sys.Date()-1,"lastyear"=Sys.Date()-365)
dbWriteTable(conSQL,"DateTest",datetest, overwrite=TRUE)

### This runs OK ###
dbExecute(conSQL, "INSERT INTO `DateTest` VALUES ('2000-01-01','1970-01-01','1969-12-31');")

### This runs OK (Dates sent off as character type)
datetest<-data.frame("today"='2000-01-01',"yesterday"='1970-01-01',"lastyear"='1969-12-31')
dbWriteTable(conSQL,"DateTest",datetest, append=TRUE)

### This runs OK (Date type, but all after 1970) ###
datetest<-data.frame("today"=as.Date('2000-01-01'),"yesterday"=as.Date('1970-01-01'),"lastyear"=as.Date('2900-01-01'))
dbWriteTable(conSQL,"DateTest",datetest, append=TRUE)

### This crashes ###
datetest<-data.frame("today"=as.Date('2000-01-01'),"yesterday"=as.Date('1970-01-01'),"lastyear"=as.Date('1969-12-31'))
dbWriteTable(conSQL,"DateTest",datetest, append=TRUE)

dbDisconnect(conSQL)
```

The obvious workaround is to use character type, but it's inconvenient when the data is already in Date format in R. Both ends can encode dates in the past but something is wrong in translation when going from R to MariaDB (the reverse works fine). Because it crashes at exactly 1969-12-31, it's probably to do with R's Date format being a negative integer before 1970-01-01. Any help is appreciated!

**Comment by krlmlr** [comment] 2018-11-26 11:01
Thanks. This works for me with the development version of _RMariaDB_, can you confirm? Install with:

```r
remotes::install_github("r-dbi/RMariaDB")
```

**Comment by AdrienMtgn** [comment] 2018-12-18 14:38
This issue is the same as #95.
@krlmlr Doestn't work for me with the development version (maybe I did something wrong tho).

`sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7600)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMariaDB_1.0.6.9000

loaded via a namespace (and not attached):
[1] bit_1.1-14      compiler_3.4.3  hms_0.4.2       DBI_1.0.0       tools_3.4.3     Rcpp_1.0.0      bit64_0.9-7     pkgconfig_2.0.2 rlang_0.3.0.1  `

**Comment by krlmlr** [comment] 2018-12-30 15:51
Closing as duplicate of #95.

**Closed by krlmlr** 2018-12-30 15:51 UTC
