### ISSUE TITLE
Bug: Incorrect Timezone Handling

### ISSUE THREAD

**Issue by jtelleria** [r-dbi/RMariaDB#93] opened 2018-04-19 14:03 UTC
I cannot report properly the bug because we have GitHub blocked at my work office, but I'll do my best:

```
session info()
RMariaDB_1.0.5
R 3.4.3
Windows 7 x64
LC_TIME=Spanish_Spain.1252
```
```
mariadbClientLibraryVersions()
5.5.1
50501
```

When I execute a procedure which manipulates dates through this 3 ways results differ!!:
* Directly from Maria SQL IDE: CALL sp_name()
* From R using odbc Package and MySQL ODBC Connector: dbExecute(con_odbc, "CALL sp_name()")
* FROM R using RMariaDB Package:
dbExecute(con_RMariaDB, "CALL sp_name()")

After thoroughly checking the results, odbc and MariaDB IDE handle properly dates, but RMariaDB does not, as I obtain as a result, for example, either using odbc or the MariaDB IDE:
"2017-07-14 00:00:00", but using RMariaDB I obtain "2017-07-13 22:00:00".

This because Spanish Timezone has 2 hour difference with regard UTC. And this is really a big issue for me, because it changes the date!... :S

Maybe I will have to move back to odbc package until this is fixed.

At home I'll be able.to provide better report.

Best,
Juan

**Comment by krlmlr** [comment] 2018-05-01 00:03
Thanks. RMariaDB does issue a `SET time_zone = '+00:00'` query. The time you're seeing is midnight in Spain converted to UTC. This shouldn't occur if your database schema uses `date` columns and not `timestamp`. Alternatively, convert the times back to your local timezone.

**Comment by jtelleria** [comment] 2018-05-01 09:43
But the problem is that I do not pass nor retrieve any results from R, and the Stored Procedure I call picks the dates from MariaDB itself, and does calculations based on such dates, which are wrong.
Maybe I could execute in my RMariaDB Connection Call the following statement:
```
SET GLOBAL time_zone = 'SYSTEM';
```

**Comment by jtelleriar** [comment] 2018-06-21 14:28
@krlmlr I've just done the validation of the previous setting on my code, and changing the TIME_ZONE of my RMariaDB Connection to SYSTEM was a bad idea, as it produced wrong results when running the procedures.
So the following is WRONG:
dbExecute(
   con,
   "SET SESSION TIME_ZONE = SYSTEM;"
)
The good news is that when executing my conflictive procedure again (Which gave me wrong results in the past) either with:
odbc (With MySQL ODBC 8.0 Connector).
RMariaDB 1.0.6
MariaDB IDE.
In all cases the results where the same (In a past time they weren't), so the conflictive setting seems to be fixed with RMariaDB 1.0.6 :) :) :)
Thank you,
Juan

**Comment by krlmlr** [comment] 2018-07-15 00:18
Thanks for the heads up. I'm considering a `time_zone` argument to `dbConnect()`, would that help?

**Comment by jtelleria** [comment] 2018-07-23 07:46
Yes, and we could port a code snippet from "odbc" package indeed, that already has this argument in dbConnect:

https://github.com/r-dbi/odbc/blob/master/man/dbConnect-OdbcDriver-method.Rd

**Comment by gitclem** [comment] 2018-12-18 20:56
I am also having this problem.  The MySQL database that I'm using has two fields that are stored as **UTC** and one in **local time** (**PST**, for the programmer's convenience.)  When the data is examine from a SQL Browser it shows the correct values.  

![image](https://user-images.githubusercontent.com/2096427/50181813-3eadcf80-02c2-11e9-97ca-262044da2063.png)

But, when I run it from R I get all the times as PST, although the TZ isn't displayed when printing the rows:

![image](https://user-images.githubusercontent.com/2096427/50181939-baa81780-02c2-11e9-90d5-d041c3b957b9.png)

but explicit printing display each shows PST

print(falls[1,"id"])
print(falls[1,"created_at"])
print(falls[1, "dutc"])
print(falls[1, "local_time"])

[1] 392
[1] "2018-12-17 09:56:01 PST"
[1] "2018-12-17 09:55:22 PST"
[1] "2018-12-17 01:55:22 PST"

It seems RMariaDB library (1.0.6) is converting the TimeZones for all the TimeStamps, to PST, even though the local_time field should NOT be shifted.

**Comment by krlmlr** [comment] 2018-12-30 14:55
@gitclem: Can you please double-check the server's time zone in your console and from within R?

```sql
SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;
```

```r
dbGetQuery(con, "SELECT @@GLOBAL.time_zone, @@SESSION.time_zone")
```

See also #80 which looks very similar.

I believe this problem will be resolved once `dbConnect()` gains a `timezone` argument as suggested above. Alternatively we might want to respect the global time zone. Closing for now.

**Closed by krlmlr** 2018-12-30 14:55 UTC

**Comment by krlmlr** [comment] 2018-12-30 15:09
@gitclem: Server time zone is still useful info for me, but isn't likely to be helpful with the problem. In your particular situation the best bet might be to set the `"tzone"` attribute for the columns.

**Comment by gitclem** [comment] 2019-01-01 19:12
Here's the result I get:
> dbGetQuery(cc, "SELECT @@GLOBAL.time_zone, @@SESSION.time_zone")
  @@GLOBAL.time_zone @@SESSION.time_zone
1                UTC              +00:00

BUT, I think you are missing how I'm using datetime info.  My data involves information about locations in a number of different time zones.  To make things simpler for the application, we've stored the LOCAL datetime, including the timezone info.

SQL browsers (Such as Squirrel) seem to respect the tz info that is stored in the DB.  When I use RMySQL to extract the datetimes, they come out as strings which also include the timezone info.  However, RMariaDB doesn't.

 I'm currently using RMySQL to work around this problem.

BTW, I was completely blindsided by this misfeature.  I had some spirited emails with my boss, as the behavior was unexpected.

**Comment by krlmlr** [comment] 2019-01-07 21:09
Thanks. I need to double-check how `RMySQL` handles this. Ideally the server's time zone should be of no importance, but I'm not familiar enough with MySQL's time zone handling.

**Comment by gitclem** [comment] 2019-01-07 21:19
RMySQL doesn't handle dates, but does pass them along as strings.  I have to do a bunch of extra stuff to get the timezone (which is stored in my DB) and then convert the string representation of datetime into a proper POSIX time.  It's ugly, but it works.  The RMariaDB just does the wrong thing.

I'm also concerned that any fix will break existing code.

**Comment by krlmlr** [comment] 2019-01-07 21:30
Where is the time zone stored in your DB?

If a bug fix breaks existing code, the code was likely expecting unreasonable behavior. Unless it's not a bug ;-)

Issue 116 has a bit more detail, I'd slightly prefer to continue discussion there (based on my initial thoughts).

**Comment by gitclem** [comment] 2019-01-07 21:44
My Time Zone info is stored in an application specific way.  I have a table of "facilities" and their corresponding time zone IDs.  I have a time zone ID to offset and TZ Name, etc.  I have to do a look up and then convert the string to a datetime:  Sometime like:

where dstring and timezonestring are retrieve via SQL query.  
`datetime <- as.POSIXct(dtstring, tz=timezonestring)`

I also get the warning from RMySQL:

"unrecognized MySQL field type 7 in column _N_ imported as character"

which I don't get with RMariaDB.  It just means (I guess) that RMySQL never got around to implementing datetime stuff...
